/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bookshopparthenope;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.stage.Stage;

/**
 * Questa classe è l'entry point dell'applicazione JavaFX "Book Shop Parthenope". È una sottoclasse della classe Application di JavaFX e implementa il metodo start(), che viene chiamato quando l'applicazione viene avviata.
 *
 * Nel metodo start() viene creato un oggetto FXMLLoader per caricare il file FXML del layout della schermata di login dell'applicazione. Viene quindi creata una nuova scena, contenente il layout caricato, che viene impostata come scena primaria dell'oggetto Stage ricevuto in input. Infine, viene mostrata la finestra di login, impostato il titolo, l'icona e la dimensione della finestra.
 */
public class App extends Application {
    public static void main(String[] args) {
        launch();
    }
    @Override
    public void start(Stage primaryStage) throws Exception {
        FXMLLoader fxmlLoader = new FXMLLoader(LoginController.class.getResource("/bookshopparthenope/gui/login.fxml"));
        Scene scene = new Scene(fxmlLoader.load(), 650, 450);
        primaryStage.setTitle("Book Shop Parthenope");
        primaryStage.setScene(scene);
        primaryStage.show();
        primaryStage.setResizable(false);
        Image icon = new Image("bookshopparthenope/gui/images/logoDesktop.png");
        primaryStage.getIcons().add(icon);

    }

}
